Environments/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

Environments/app/core/urls.py
from django.urls import path
from core.views import HomeTemplateView, EstoqueListView, \
    EstoqueUpdateView, EstoqueCreateView, \
    EstoqueDeleteView

app_name = 'core'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name="home"),
    path('estoque/cadastrar', EstoqueCreateView.as_view(), name="cadastra_item"),
    path('estoque/', EstoqueListView.as_view(), name="lista_items"),
    path('estoque/<pk>', EstoqueUpdateView.as_view(), name="atualiza_item"),
    path('estoque/excluir/<pk>', EstoqueDeleteView.as_view(), name="deleta_item"),
]

Environments/app/core/models.py
from django.db import models

class Estoque(models.Model):
    codigo = models.IntegerField()
    nome = models.CharField(max_length=130)
    quantidade = models.IntegerField()

Environments/app/core/forms.py
from core.models import Estoque
from django import forms


class InsereItemForm(forms.ModelForm):

    class Meta:
        model = Estoque

        fields = [
            'codigo',
            'nome',
            'quantidade'
        ]

Environments/app/core/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, TemplateView
from django.shortcuts import render
from .models import Estoque
from core.forms import InsereItemForm


class HomeTemplateView(TemplateView):

    template_name = 'index.html'


class EstoqueListView(ListView):
    model = Estoque
    template_name = 'lista.html'
    context_object_name = "items"


class EstoqueCreateView(CreateView):
    template_name = "cria.html"
    model = Estoque
    form_class = InsereItemForm
    success_url = reverse_lazy("core:lista_items")


class EstoqueUpdateView(UpdateView):
    template_name = "atualiza.html"
    model = Estoque
    fields = '__all__'
    context_object_name = 'item'
    success_url = reverse_lazy("core:lista_items")


class EstoqueDeleteView(DeleteView):
    template_name = "exclui.html"
    model = Estoque
    fields = '__all__'
    context_object_name = 'item'
    success_url = reverse_lazy("core:lista_items")

Environments/app/core/templates/atualiza.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="post">
        {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

        <button>Enviar</button>
    </form>
{% endblock content %}

Environments/app/core/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Controle de Estoque sofisticado</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
    body {
        color: #566787;
		background: #f5f5f5;
		font-family: 'Varela Round', sans-serif;
		font-size: 13px;
	}
	.table-wrapper {
        background: #fff;
        padding: 20px 25px;
        margin: 30px 0;
		border-radius: 3px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
	.table-title {        
		padding-bottom: 15px;
		background: #435d7d;
		color: #fff;
		padding: 16px 30px;
		margin: -20px -25px 10px;
		border-radius: 3px 3px 0 0;
    }
    .table-title h2 {
		margin: 5px 0 0;
		font-size: 24px;
	}
	.table-title .btn-group {
		float: right;
	}
	.table-title .btn {
		color: #fff;
		float: right;
		font-size: 13px;
		border: none;
		min-width: 50px;
		border-radius: 2px;
		border: none;
		outline: none !important;
		margin-left: 10px;
	}
	.table-title .btn i {
		float: left;
		font-size: 21px;
		margin-right: 5px;
	}
	.table-title .btn span {
		float: left;
		margin-top: 2px;
	}
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
		padding: 12px 15px;
		vertical-align: middle;
    }
	table.table tr th:first-child {
		width: 60px;
	}
	table.table tr th:last-child {
		width: 100px;
	}
    table.table-striped tbody tr:nth-of-type(odd) {
    	background-color: #fcfcfc;
	}
	table.table-striped.table-hover tbody tr:hover {
		background: #f5f5f5;
	}
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }	
    table.table td:last-child i {
		opacity: 0.9;
		font-size: 22px;
        margin: 0 5px;
    }
	table.table td a {
		font-weight: bold;
		color: #566787;
		display: inline-block;
		text-decoration: none;
		outline: none !important;
	}
	table.table td a:hover {
		color: #2196F3;
	}
	table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #F44336;
    }
    table.table td i {
        font-size: 19px;
    }
	table.table .avatar {
		border-radius: 50%;
		vertical-align: middle;
		margin-right: 10px;
	}
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 13px;
        min-width: 30px;
        min-height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 2px !important;
        text-align: center;
        padding: 0 6px;
    }
    .pagination li a:hover {
        color: #666;
    }	
    .pagination li.active a, .pagination li.active a.page-link {
        background: #03A9F4;
    }
    .pagination li.active a:hover {        
        background: #0397d6;
    }
	.pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 10px;
        font-size: 13px;
    }    
	/* Custom checkbox */
	.custom-checkbox {
		position: relative;
	}
	.custom-checkbox input[type="checkbox"] {    
		opacity: 0;
		position: absolute;
		margin: 5px 0 0 3px;
		z-index: 9;
	}
	.custom-checkbox label:before{
		width: 18px;
		height: 18px;
	}
	.custom-checkbox label:before {
		content: '';
		margin-right: 10px;
		display: inline-block;
		vertical-align: text-top;
		background: white;
		border: 1px solid #bbb;
		border-radius: 2px;
		box-sizing: border-box;
		z-index: 2;
	}
	.custom-checkbox input[type="checkbox"]:checked + label:after {
		content: '';
		position: absolute;
		left: 6px;
		top: 3px;
		width: 6px;
		height: 11px;
		border: solid #000;
		border-width: 0 3px 3px 0;
		transform: inherit;
		z-index: 3;
		transform: rotateZ(45deg);
	}
	.custom-checkbox input[type="checkbox"]:checked + label:before {
		border-color: #03A9F4;
		background: #03A9F4;
	}
	.custom-checkbox input[type="checkbox"]:checked + label:after {
		border-color: #fff;
	}
	.custom-checkbox input[type="checkbox"]:disabled + label:before {
		color: #b8b8b8;
		cursor: auto;
		box-shadow: none;
		background: #ddd;
	}
	/* Modal styles */
	.modal .modal-dialog {
		max-width: 400px;
	}
	.modal .modal-header, .modal .modal-body, .modal .modal-footer {
		padding: 20px 30px;
	}
	.modal .modal-content {
		border-radius: 3px;
	}
	.modal .modal-footer {
		background: #ecf0f1;
		border-radius: 0 0 3px 3px;
	}
    .modal .modal-title {
        display: inline-block;
    }
	.modal .form-control {
		border-radius: 2px;
		box-shadow: none;
		border-color: #dddddd;
	}
	.modal textarea.form-control {
		resize: vertical;
	}
	.modal .btn {
		border-radius: 2px;
		min-width: 100px;
	}	
	.modal form label {
		font-weight: normal;
	}	
</style>
<script type="text/javascript">
$(document).ready(function(){
	// Activate tooltip
	$('[data-toggle="tooltip"]').tooltip();
	
	// Select/Deselect checkboxes
	var checkbox = $('table tbody input[type="checkbox"]');
	$("#selectAll").click(function(){
		if(this.checked){
			checkbox.each(function(){
				this.checked = true;                        
			});
		} else{
			checkbox.each(function(){
				this.checked = false;                        
			});
		} 
	});
	checkbox.click(function(){
		if(!this.checked){
			$("#selectAll").prop("checked", false);
		}
	});
});
</script>
</head>
<body>

    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
						<h2>Gerenciar <b>Estoque</b></h2>
                        </div>
					<div class="col-sm-6">
						<a href="{% url 'core:home' %}" class="btn btn-primary" data-toggle="modal"><i class="material-icons">home</i> <span>Home</span></a>
						<a href="{% url 'core:lista_items' %}" class="btn btn-info" data-toggle="modal"><i class="material-icons">list</i> <span>Listar Items</span></a>
						<a href="{% url 'core:cadastra_item' %}" class="btn btn-success" data-toggle="modal"><i class="material-icons">add</i> <span>Adicionar Item</span></a>
					</div>
                </div>
            </div>
        {% block content %}
        {% endblock content %}
</body>
<footer class="page-footer font-small special-color-dark pt-4" style="margin-top:5%">

  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> Canario.com</a>
  </div>

</footer>
</html>

Environments/app/core/templates/cria.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Página de Criação de Item</h1>

    <form method="post" class="form-horizontal">
        {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

        <button class="btn btn-primary">Enviar</button>
    </form>
{% endblock content %}

Environments/app/core/templates/exclui.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Página de Exclusão de Funcionário</h1>

    <form method="post" style="border: 1px solid #AAA; margin: 64px auto; padding: 32px; width: 50%;">
        {% csrf_token %}

        Você tem certeza que quer excluir o item <b>{{ item.nome }}</b>? <br><br>

        <button type="button">
            <a href="{% url 'core:lista_items' %}">Cancelar</a>
        </button>
        <button>Excluir</button>
    </form>
{% endblock content %}

Environments/app/core/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Bem vindo ao controle de estoque</h1>
    <p class="lead">Escolha a opção acima para começar.</p>
  </div>
</div>

{% endblock content %}

Environments/app/core/templates/lista.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div style="max-width: 50%;">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th><b>Código</b></th>
                    <th><b>Nome</b></th>
                    <th><b>Quantidade</b></th>
                    <th><b>Atualizar</b></th>
                    <th><b>Apagar</b></th>
                </tr>
            </thead>

            <tbody>
                {% for item in items %}
                    <tr>
                        <th>{{ item.codigo }}</th>
                        <th>{{ item.nome }}</th>
                        <th>{{ item.quantidade }}</th>
                        <th><a href="{% url 'core:atualiza_item' pk=item.id %}"><i class="material-icons">edit</i></a></th>
                        <th><a href="{% url 'core:deleta_item' pk=item.id %}"><i class="material-icons">delete</i></a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

{% endblock content %}